### PR TITLE
Fixes to kalman filter and implementation for adaptive Q and R noise covariance estimation

### PR DESCRIPTION
**Pull request by henriksod**
Reopening since it seemed to get some attention.
Rebased to latest master, I do not know of any other changes to the repo. Please let me know.

Fixed noise covariance matrices so they are not varied based on bounding box location. Fixed delta time of predictions from constant 1 second to varied based on the frequency of predictions, this should increase performance.

Implemented adaptive kalman filter for Q and R estimation, based on [this article](https://arxiv.org/ftp/arxiv/papers/1702/1702.00884.pdf).

In my experiments, I found that the additions I made gave better results in a practical scenario. When tracking something, you usually want to take into account the delta time between kalman updates. Also, I made it not necessary any more to have to tune the filter to find the optimal Q and R noise matrix parameters, should hopefully give better results in the end.

### CODE REVIEW

**Comment by mikel-brostrom** [comment]
Nice! Let's check this out now that MOT17 evaluation is working (MOT16 is now deprecated)

**Comment by henriksod** [comment]
Great, automated tests :-D Will fix the issues asap...

**Comment by mikel-brostrom** [comment]
:rocket:

**Comment by mikel-brostrom** [comment]
ok, StrongSORT passes. Evaluating...

**Comment by mikel-brostrom** [comment]
Results

```
HOTA: exp157-pedestrian            HOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      RHOTA     HOTA(0)   LocA(0)   HOTALocA(0)
MOT17-04-FRCNN                     56.828    59.084    55.314    64.135    76.17     59.037    79.775    81.036    59.465    75.185    75.299    56.614    
MOT17-05-FRCNN                     41.415    38.995    44.093    41.89     74.353    51.782    70.226    81.661    42.97     53.571    76.656    41.066    
MOT17-09-FRCNN                     55.411    60.805    50.546    66.247    80.65     55.392    78.715    85.817    57.859    68.481    82.145    56.254    
MOT17-10-FRCNN                     48.471    50.289    46.881    54.027    75.128    50.733    78.102    80.568    50.32     64.636    75.722    48.943    
MOT17-11-FRCNN                     54.997    58.862    51.521    70.479    73.105    56.783    81.981    86.782    60.253    66.074    83.332    55.061    
MOT17-13-FRCNN                     46.292    43.033    50.182    46.795    72.34     54.747    77.266    80.239    48.406    61.119    74.802    45.718    
COMBINED                           53.366    54.444    52.828    59.713    75.444    57.16     79.869    81.901    56.081    69.346    76.65     53.154    

CLEAR: exp157-pedestrian           MOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag      
MOT17-04-FRCNN                     69.533    78.46     69.704    76.952    91.392    48.193    36.145    15.663    52.958    36596     10961     3447      81        40        30        13        464       
MOT17-05-FRCNN                     45.381    78.979    46.191    51.265    90.993    19.549    57.895    22.556    34.605    3546      3371      351       56        26        77        30        238       
MOT17-09-FRCNN                     68.563    84.495    69.333    75.737    92.204    50        50        0         56.82     4033      1292      341       41        13        13        0         115       
MOT17-10-FRCNN                     62.583    77.232    63.05     67.482    93.837    29.825    59.649    10.526    47.219    8664      4175      569       60        17        34        6         638       
MOT17-11-FRCNN                     62.092    85.394    62.431    79.419    82.379    44        42.667    13.333    50.492    7494      1942      1603      32        33        32        10        163       
MOT17-13-FRCNN                     52.792    76.814    53.35     59.019    91.236    30        41.818    28.182    39.107    6871      4771      660       65        33        46        31        282       
COMBINED                           63.914    79.296    64.272    71.71     90.602    33.471    47.934    18.595    49.068    67204     26512     6971      335       162       232       90        1900      

Identity: exp157-pedestrian        IDF1      IDR       IDP       IDTP      IDFN      IDFP      
MOT17-04-FRCNN                     68.66     63.236    75.102    30073     17484     9970      
MOT17-05-FRCNN                     56.094    43.848    77.829    3033      3884      864       
MOT17-09-FRCNN                     67.904    61.84     75.286    3293      2032      1081      
MOT17-10-FRCNN                     65.495    56.297    78.284    7228      5611      2005      
MOT17-11-FRCNN                     61.069    59.972    62.207    5659      3777      3438      
MOT17-13-FRCNN                     62.202    51.22     79.179    5963      5679      1568      
COMBINED                           65.815    58.954    74.485    55249     38467     18926     

Count: exp157-pedestrian           Dets      GT_Dets   IDs       GT_IDs    
MOT17-04-FRCNN                     40043     47557     169       83        
MOT17-05-FRCNN                     3897      6917      125       133       
MOT17-09-FRCNN                     4374      5325      53        26        
MOT17-10-FRCNN                     9233      12839     104       57        
MOT17-11-FRCNN                     9097      9436      169       75        
MOT17-13-FRCNN                     7531      11642     141       110       
COMBINED                           74175     93716     761       484
```

**Comment by henriksod** [comment]
I see that we can do some improvements in `track.py` under root.

```python

if det is not None and len(det):
                # Rescale boxes from img_size to im0 size
                det[:, :4] = scale_coords(im.shape[2:], det[:, :4], im0.shape).round()  # xyxy

                # Print results
                for c in det[:, -1].unique():
                    n = (det[:, -1] == c).sum()  # detections per class
                    s += f"{n} {names[int(c)]}{'s' * (n > 1)}, "  # add to string

                # pass detections to strongsort
                t4 = time_sync()
                outputs[i] = tracker_list[i].update(det.cpu(), im0, time_sync())
                t5 = time_sync()
                dt[3] += t5 - t4

                # draw boxes for visualization
                if len(outputs[i]) > 0:
                    # TODO (henriksod): The class can be stored in the objects instead!
                    for j, (output, conf) in enumerate(zip(outputs[i], det[:, 4])): 
    
                        bboxes = output[0:4]
                        id = output[4]
                        cls = output[5]

                        if save_txt:
                            # to MOT format
                            bbox_left = output[0]
                            bbox_top = output[1]
                            bbox_w = output[2] - output[0]
                            bbox_h = output[3] - output[1]
                            # Write MOT compliant results to file
                            with open(txt_path + '.txt', 'a') as f:
                                f.write(('%g ' * 10 + '\n') % (frame_idx + 1, id, bbox_left,  # MOT format
                                                               bbox_top, bbox_w, bbox_h, -1, -1, -1, i))

                        if save_vid or save_crop or show_vid:  # Add bbox to image
                            c = int(cls)  # integer class
                            id = int(id)  # integer id
                            label = None if hide_labels else (f'{id} {names[c]}' if hide_conf else \
                                (f'{id} {conf:.2f}' if hide_class else f'{id} {names[c]} {conf:.2f}'))
                            annotator.box_label(bboxes, label, color=colors(c, True))
                            if save_crop:
                                txt_file_name = txt_file_name if (isinstance(path, list) and len(path) > 1) else ''
                                save_one_box(bboxes, imc, file=save_dir / 'crops' / txt_file_name / names[c] / f'{id}' / f'{p.stem}.jpg', BGR=True)

                LOGGER.info(f'{s}Done. yolo:({t3 - t2:.3f}s), {tracking_method}:({t5 - t4:.3f}s)')

            else:
                # TODO (henriksod): Here we can perform tracker predictions and send for evaluation!
                LOGGER.info('No detections')

```

**Comment by mikel-brostrom** [comment]
Yup, it would be nice to enable KF predictions ahead when there are no detector predictions :smile: . Maybe make this toggle-able from `track.py`?

**Review by lhfabc9 — APPROVED** [review]

**Comment by mikel-brostrom** [comment]
```
HOTA: exp240-pedestrian            HOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      RHOTA     HOTA(0)   LocA(0)   HOTALocA(0)
MOT17-04-FRCNN                     45.577    40.939    51.118    44.415    76.758    55.408    80.503    84.2      47.583    58.419    76.692    44.802    
MOT17-05-FRCNN                     6.7035    2.3802    18.9      2.4006    66.156    20.014    74.212    80.912    6.7318    9.0495    73.449    6.6467    
MOT17-09-FRCNN                     52.933    54.971    51.09     61.256    76.088    57.506    75.99     83.919    55.941    67.498    79.294    53.522    
MOT17-10-FRCNN                     47.704    45.697    49.959    49.675    72.016    54.678    74.179    79.212    49.812    66.561    72.537    48.282    
MOT17-11-FRCNN                     52.441    48.867    56.49     59.777    67.382    61.976    81.392    84.389    58.099    67.928    76.76     52.142    
MOT17-13-FRCNN                     40.637    32.814    50.607    34.833    73.787    54.899    75.981    80.786    41.949    53.109    75.293    39.987    
COMBINED                           45.201    39.615    51.942    43.348    74.16     56.675    79.456    83.041    47.391    58.617    76.061    44.585    

CLEAR: exp240-pedestrian           MOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag      
MOT17-04-FRCNN                     39.723    83.845    39.906    48.884    84.483    19.277    45.783    34.94     31.826    23248     24309     4270      87        16        38        29        429       
MOT17-05-FRCNN                     2.2119    78.261    2.2409    2.9348    80.876    0         3.7594    96.241    1.5739    203       6714      48        2         0         5         128       7         
MOT17-09-FRCNN                     61.521    82.031    61.991    71.249    88.5      50        46.154    3.8462    48.718    3794      1531      493       25        13        12        1         62        
MOT17-10-FRCNN                     53.01     76.1      53.509    61.243    88.787    29.825    52.632    17.544    38.373    7863      4976      993       64        17        30        10        317       
MOT17-11-FRCNN                     42.645    84.035    42.847    65.78     74.149    32        26.667    41.333    32.143    6207      3229      2164      19        24        20        31        54        
MOT17-13-FRCNN                     38.962    77.576    39.564    43.386    91.903    21.818    33.636    44.545    29.234    5051      6591      445       70        24        37        49        193       
COMBINED                           40.213    81.701    40.498    49.475    84.642    19.421    29.339    51.24     31.16     46366     47350     8413      267       94        142       248       1062      

Identity: exp240-pedestrian        IDF1      IDR       IDP       IDTP      IDFN      IDFP      
MOT17-04-FRCNN                     52.926    41.775    72.196    19867     27690     7651      
MOT17-05-FRCNN                     5.4408    2.8191    77.689    195       6722      56        
MOT17-09-FRCNN                     67.998    61.371    76.23     3268      2057      1019      
MOT17-10-FRCNN                     63.987    54.062    78.376    6941      5898      1915      
MOT17-11-FRCNN                     60.01     56.624    63.827    5343      4093      3028      
MOT17-13-FRCNN                     53.799    39.598    83.879    4610      7032      886       
COMBINED                           54.176    42.921    73.43     40224     53492     14555     

Count: exp240-pedestrian           Dets      GT_Dets   IDs       GT_IDs    
MOT17-04-FRCNN                     27518     47557     109       83        
MOT17-05-FRCNN                     251       6917      15        133       
MOT17-09-FRCNN                     4287      5325      44        26        
MOT17-10-FRCNN                     8856      12839     86        57        
MOT17-11-FRCNN                     8371      9436      98        75        
MOT17-13-FRCNN                     5496      11642     105       110       
COMBINED                           54779     93716     457       484
```

**Comment by henriksod** [comment]
Sounds like a good idea

**Comment by henriksod** [comment]
I will split it into 3:
1. Adaptive Kalman Filter
2. True delta time to prediction step
3. Perform predictions when no detections are present

**Comment by mikel-brostrom** [comment]
I believe this would be the best, so that we can make an ablation study to see what effect each contribution has on MOT17. Then  we could decide what to merge to master :smile:

**Comment by mikel-brostrom** [comment]
I tried the predictions ahead myself by adding this just after the track update in `track.py`;

```python
outputs_ = []
for track in tracker_list[i].tracker.tracks :
    if not track.is_confirmed():
        continue
    # check the track was not updated and that it didn't make more than 2 predictions ahead
    if track.time_since_update > 1 and track.preds_ahead_made < 2:
        #"print('predicting', track)
        track.predict(track.kf)
        track.preds_ahead_made = track.preds_ahead_made + 1 
        box = track.to_tlwh()
        x1, y1, x2, y2 = tracker_list[i]._tlwh_to_xyxy(box)
        track_id = track.track_id
        class_id = track.class_id
        conf = track.conf
        outputs_.append(np.array([x1, y1, x2, y2, track_id, class_id, conf]))
if len(outputs_) > 0:
    outputs_ = np.stack(outputs_, axis=0)
    outputs[i] = np.concatenate((outputs[i], outputs_), axis=0)
```

So I make a maximum of 1 preds ahead for the tracks without association. My results:

```
HOTA: exp56-pedestrian             HOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
MOT17-04-FRCNN                     60.912    59.013    63.401    64.145    76.005    68.899    78.903    80.979    63.724    81.257    75.16     61.072    
MOT17-05-FRCNN                     40.289    39.095    41.642    42.175    73.686    52.401    63.925    81.486    41.897    52.065    76.413    39.785    
MOT17-09-FRCNN                     55.311    60.301    50.789    65.781    80.34     55.328    78.685    85.692    57.795    68.744    81.813    56.242    
MOT17-10-FRCNN                     50.845    50.202    51.678    54.061    74.77     56.693    75.978    80.455    52.85     67.848    75.573    51.275    
MOT17-11-FRCNN                     62.709    58.586    67.337    70.524    72.578    74.546    81.937    86.683    68.902    75.165    83.108    62.468    
MOT17-13-FRCNN                     46.693    43.079    50.999    47.004    71.907    56.871    74.08     80.129    48.91     61.806    74.565    46.086    
COMBINED                           56.751    54.346    59.815    59.748    75.141    65.871    78.415    81.814    59.698    74.037    76.472    56.618    

CLEAR: exp56-pedestrian            MOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag      
MOT17-04-FRCNN                     69.725    78.485    69.853    77.124    91.384    50.602    33.735    15.663    53.131    36678     10879     3458      61        42        28        13        548       
MOT17-05-FRCNN                     45.366    78.771    46.306    51.771    90.452    19.549    63.158    17.293    34.376    3581      3336      378       65        26        84        23        253       
MOT17-09-FRCNN                     67.981    84.442    68.883    75.38     92.064    50        50        0         56.254    4014      1311      346       48        13        13        0         143       
MOT17-10-FRCNN                     62.52     77.021    63.144    67.723    93.666    28.07     61.404    10.526    46.958    8695      4144      588       80        16        35        6         665       
MOT17-11-FRCNN                     61.488    85.316    61.816    79.493    81.808    46.667    40        13.333    49.815    7501      1935      1668      31        35        30        10        201       
MOT17-13-FRCNN                     52.439    76.698    53.152    59.26     90.657    30        41.818    28.182    38.631    6899      4743      711       83        33        46        31        318       
COMBINED                           63.864    79.244    64.257    71.885    90.406    34.091    48.76     17.149    48.943    67368     26348     7149      368       165       236       83        2128      

Identity: exp56-pedestrian         IDF1      IDR       IDP       IDTP      IDFN      IDFP      
MOT17-04-FRCNN                     77.327    71.293    84.475    33905     13652     6231      
MOT17-05-FRCNN                     54.321    42.706    74.615    2954      3963      1005      
MOT17-09-FRCNN                     67.981    61.822    75.505    3292      2033      1068      
MOT17-10-FRCNN                     69.677    60.028    83.023    7707      5132      1576      
MOT17-11-FRCNN                     74.346    73.294    75.428    6916      2520      2253      
MOT17-13-FRCNN                     63.058    52.139    79.763    6070      5572      1540      
COMBINED                           72.333    64.924    81.651    60844     32872     13673

Count: exp56-pedestrian            Dets      GT_Dets   IDs       GT_IDs    
MOT17-04-FRCNN                     40136     47557     132       83        
MOT17-05-FRCNN                     3959      6917      104       133       
MOT17-09-FRCNN                     4360      5325      52        26        
MOT17-10-FRCNN                     9283      12839     97        57        
MOT17-11-FRCNN                     9169      9436      152       75        
MOT17-13-FRCNN                     7610      11642     134       110       
COMBINED                           74517     93716     671       484 
```

A bit worse... Will try with one prediction ahead as well

**Comment by Stephen-Ning** [comment]
Adaptive Adjustment of Noise Covariance in Kalman  Filter for Dynamic State Estimation
This article is improved based on Extended Kalman. You don't use Extended Kalman in your code, just add adaptive Kalman, right?

**Comment by Stephen-Ning** [comment]
> Adaptive Adjustment of Noise Covariance in Kalman Filter for Dynamic State Estimation
> This article is improved based on Extended Kalman. You don't use Extended Kalman in your code, just add adaptive Kalman, right?

**Comment by henriksod** [comment]
Correct! Isn't it so, that this model would result in the same model as in ordinary KF if you were to derive the Jacobian matrices?

**Comment by Stephen-Ning** [comment]
> Correct! Isn't it so, that this model would result in the same model as in ordinary KF if you were to derive the Jacobian matrices?

May I ask you a question? In theory, I do not understand what adaptive Kalman filtering will bring to tracking.

**Comment by henriksod** [comment]
> > Correct! Isn't it so, that this model would result in the same model as in ordinary KF if you were to derive the Jacobian matrices?
> 
> May I ask you a question? In theory, I do not understand what adaptive Kalman filtering will bring to tracking.We look forward to your reply!

In a Kalman filter, you have additive noise in the covariance estimation step. This noise is typically tuned empirically to fit the model used for estimation. This adaptive approach,  introduced by th paper I linked to, adaptively calculates the noise matrices based on the residual error, left over from the innovation in the update step. The purpose is, that the model of the target in which you are trying to track is ambiguous, since there is no restriction on what you can track. With that said, you cannot assume a noise model unless you specify what the tracker is supposed to track, and thus update the model accordingly.

**Comment by Stephen-Ning** [comment]
Thank you for your answer. got it!

**Comment by Stephen-Ning** [comment]
> > > Correct! Isn't it so, that this model would result in the same model as in ordinary KF if you were to derive the Jacobian matrices?
> > 
> > 
> > May I ask you a question? In theory, I do not understand what adaptive Kalman filtering will bring to tracking.We look forward to your reply!
> 
> In a Kalman filter, you have additive noise in the covariance estimation step. This noise is typically tuned empirically to fit the model used for estimation. This adaptive approach, introduced by th paper I linked to, adaptively calculates the noise matrices based on the residual error, left over from the innovation in the update step. The purpose is, that the model of the target in which you are trying to track is ambiguous, since there is no restriction on what you can track. With that said, you cannot assume a noise model unless you specify what the tracker is supposed to track, and thus update the model accordingly.

Kf For the changes of Q R noise caused by nonlinear motion and occlusion, does adaptive kf have any effect on these effects?

**Comment by mikel-brostrom** [comment]
Quite good boosts for KL preds and updates for tracks with no associations

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/wiki/Effect-of-KF-updates-ahead-for-tracks-with-no-associations,-on-MOT17

**Comment by Stephen-Ning** [comment]
> > > Correct! Isn't it so, that this model would result in the same model as in ordinary KF if you were to derive the Jacobian matrices?
> > 
> > 
> > May I ask you a question? In theory, I do not understand what adaptive Kalman filtering will bring to tracking.We look forward to your reply!
> 
> In a Kalman filter, you have additive noise in the covariance estimation step. This noise is typically tuned empirically to fit the model used for estimation. This adaptive approach, introduced by th paper I linked to, adaptively calculates the noise matrices based on the residual error, left over from the innovation in the update step. The purpose is, that the model of the target in which you are trying to track is ambiguous, since there is no restriction on what you can track. With that said, you cannot assume a noise model unless you specify what the tracker is supposed to track, and thus update the model accordingly.

hey，henriksod！Adaptive Kalman filtering has worked very well in my scene!But I can't understand one thing.
Calculating Rk requires residual, calculating residual requires Xk (posterior estimation), calculating Xk requires Kalman gain, and calculating Kalman gain requires Rk, which is a bit contradictory! I have reviewed your code and found that the residual is only calculated after updating the state and covariance, which means that the Kalman gain at k-1 is calculated using R. Looking forward to your reply!

**Comment by Stephen-Ning** [comment]
image
Can you provide the state covariance formula as shown in the figure? I checked the code and it's not the original covariance formula P '=(I-KH) P.

**Pull request closed without merging**
