### PR TITLE
changes

### PR DESCRIPTION
**Pull request by Pieterm93**
I added it as a separate tracker now. Apart of adding it, I only changed the examples/track.py to add the option to select the changed OCSort.

### CODE REVIEW

**Comment by mikel-brostrom** [comment]
Thx! Will get this merged asap. I am planning a huge refactor to get this into all the trackers by activating a flag

**Comment by Pieterm93** [comment]
I'm getting slightly different results in the amount of tracks when only tracking one class with the trackers in dicts. trying to figure out why, as it shouldn't make a difference in this case.

Also, the second association round should also be based on classes, so this part of the code should probably be below the split of the detections based on detection class

**Comment by mikel-brostrom** [comment]
> I'm getting slightly different results in the amount of tracks when only tracking one class with the trackers in dicts.

Is the amount of detection for the class in `dets_dict` the same as the input dets? You could  `assert` this :smile:

**Comment by mikel-brostrom** [comment]
First goes the [big refactor](https://github.com/mikel-brostrom/yolo_tracking/pull/986) in order to make this easier

**Comment by Pieterm93** [comment]
It had to do with frames with no detections. Those have no class_id, so it's not updating the specific trackers

**Comment by mikel-brostrom** [comment]
> It had to do with frames with no detections. Those have no class_id, so it's not updating the specific trackers

Make sense

```python
if dets.size == 0:
    # ...
else:
    dets_dict = {class_id: np.array([det for det in dets if det[-1] == class_id]) for class_id in set(det[-1] for det in dets)}
```

**Comment by Pieterm93** [comment]
Looks good! Did it like this now and it works, but will try your variation too

`dets_dict = {class_id: np.array([det for det in dets if det[5] == class_id]) for class_id in set(det[5] for det in dets)}

        ## classes with detections in current frame
        detected_classes = set(dets_dict.keys())  
        ## classes with active trackers
        active_classes = {k for k, v in self.trackers.items() if v}  
        ## tracker classes to be updated for current frame
        relevant_classes = active_classes.union(detected_classes)

        for class_id in relevant_classes:
            dets = dets_dict.get(class_id, np.empty((0, 6)))`

**Comment by mikel-brostrom** [comment]
Nvm my proposed solution, not working

**Comment by mikel-brostrom** [comment]
But all the classes have to be updated. No matter if they are active or not. Otherwise they never die.

**Comment by Pieterm93** [comment]
If they don't contain any live tracks, adding empty detections to them wouldn't do anything right? If they do contain tracks, the empty detections will be added

**Comment by mikel-brostrom** [comment]
`If they don't contain any live tracks, adding empty detections to them wouldn't do anything right?`

Other trackers have different states for their tracks: active, unactive... But `OCSORT` this is the case. I am mixing up trackers...

**Comment by mikel-brostrom** [comment]
I have something working based on your suggestions:

```python
class PerClassDecorator:
    def __init__(self, method):
        self.update = method
        print(self.update)
    def __get__(self, instance, owner):
        def wrapper(*args, **kwargs):
            modified_args = list(args)
            dets = modified_args[0]
            im = modified_args[1]

            # input one class of detections at a time in order to not mix them up
            if instance.per_class is True and dets.size != 0:
                dets_dict = {class_id: np.array([det for det in dets if det[5] == class_id]) for class_id in set(det[5] for det in dets)}
                # get unique classes in predictions
                detected_classes = set(dets_dict.keys())  
                # get unque classes with active trackers
                active_classes = set([tracker.cls for tracker in instance.trackers])
                # get tracks that are both active and in the current detections
                relevant_classes = active_classes.union(detected_classes)
                
                mc_dets = np.empty(shape=(0, 7))
                for class_id in relevant_classes:
                    modified_args[0] = np.array(dets_dict.get(int(class_id), np.empty((0, 6))))
                    dets = self.update(instance, modified_args[0], im)
                    if dets.size != 0:
                        mc_dets = np.append(mc_dets, dets, axis=0)
            else:
                mc_dets = self.update(instance, *modified_args, **kwargs)
            return mc_dets
        return wrapper
```

this can be applied to any tracker, just decorate `update()`, like this:

```python
@PerClassDecorator
    def update(self, dets, im0):
```

**Comment by mikel-brostrom** [comment]
I will close down this PR. I have merged you work into https://github.com/mikel-brostrom/yolo_tracking/pull/997 and then adapted it based on our discussion into a toggle'able decorator. your contribution will be seen in the comming release :smile:. Thank you for contributing to this repo :rocket:

**Pull request closed without merging**
