### PR TITLE
[Draft] MOT_Challenge correct format

### PR DESCRIPTION
**Pull request by johnnynunez**

### CODE REVIEW

**Comment by mikel-brostrom** [comment]
Make total sense to accumulate MOT results per frame till the end of the sequence and then write

**Comment by mikel-brostrom** [comment]
Aaand completely identical metric results as previously 😄. Merging 🚀

**Comment by mikel-brostrom** [comment]
Thanks for contributing to this repo @johnnynunez!

**Comment by johnnynunez** [comment]
> Make total sense to accumulate MOT results per frame till the end of the sequence and then write

Also mot challenge format it is all integers except confidence.
format: 
MOT 1.1
```
# frame_id, track_id, x, y, w, h, "not ignored", class_id, visibility, <skipped>
```
from TrackEval:
```<frame>, <id>, <bb_left>, <bb_top>, <bb_width>, <bb_height>, <conf>, <x>, <y>, <z>
The conf value contains the detection confidence in the det.txt files. For the ground truth, it acts as a flag whether the entry is to be considered. A value of 0 means that this particular instance is ignored in the evaluation, while any other value can be used to mark it as active. For submitted results, all lines in the .txt file are considered. The world coordinates x,y,z are ignored for the 2D challenge and can be filled with -1. Similarly, the bounding boxes are ignored for the 3D challenge. However, each line is still required to contain 10 values.```

example MOT17/MOT20:
722,1,547,252,68,145,1,1,0.092317
723,1,548,252,68,145,1,1,0.092317
724,1,550,252,68,145,1,1,0.089339
725,1,552,252,68,145,1,1,0.089339
726,1,554,252,68,145,1,1,0.086361
727,1,556,252,68,145,1,1,0.086361

**Comment by johnnynunez** [comment]
It is a draft still, because I see that not always works:
```
Traceback (most recent call last):
  File "/Users/johnny/Projects/yolo_tracking/tracking/generate_mot_results.py", line 170, in <module>
    run_generate_mot_results(None)
  File "/Users/johnny/Projects/yolo_tracking/tracking/generate_mot_results.py", line 166, in run_generate_mot_results
    generate_mot_results(opt)
  File "/Users/johnny/Projects/yolo_tracking/tracking/generate_mot_results.py", line 83, in generate_mot_results
    all_mot_results = np.vstack(all_mot_results)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in vstack
  File "/Users/johnny/miniconda3/envs/track/lib/python3.11/site-packages/numpy/core/shape_base.py", line 296, in vstack
    return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 9 and the array at index 1000 has size 1

```

**Comment by mikel-brostrom** [comment]
ooh, I see. The returned np array could be empty, for example:

https://github.com/mikel-brostrom/yolo_tracking/blob/37716984952e066391b1700590595b7c70d9071c/boxmot/trackers/ocsort/ocsort.py#L384

So if you check it is empty here:

https://github.com/mikel-brostrom/yolo_tracking/blob/37716984952e066391b1700590595b7c70d9071c/tracking/generate_mot_results.py#L77

such that nothing is appended to `all_mot_results`, I believe it would solve it

**Comment by mikel-brostrom** [comment]
Pull and try it out, it may work for you

**Comment by johnnynunez** [comment]
I'm trying :) also FYI, it works with mps

**Comment by johnnynunez** [comment]
I have this error now:
@mikel-brostrom 
```
/Users/johnny/Projects/yolo_tracking/tracking/generate_mot_results.py:48: UserWarning: loadtxt: input contained no data: "/Users/johnny/Projects/yolo_tracking/runs/dets_n_embs/yolov8s/dets/.DS_Store.txt"
  dets = np.loadtxt(args.dets_file_path, skiprows=1)  # skiprows=1 skips the header row
/Users/johnny/Projects/yolo_tracking/tracking/generate_mot_results.py:49: UserWarning: loadtxt: input contained no data: "/Users/johnny/Projects/yolo_tracking/runs/dets_n_embs/yolov8s/embs/clip_market1501/.DS_Store.txt"
  embs = np.loadtxt(args.embs_file_path)  # skiprows=1 skips the header row
Traceback (most recent call last):
  File "/Users/johnny/Projects/yolo_tracking/tracking/generate_mot_results.py", line 171, in <module>
    run_generate_mot_results(None)
  File "/Users/johnny/Projects/yolo_tracking/tracking/generate_mot_results.py", line 167, in run_generate_mot_results
    generate_mot_results(opt)
  File "/Users/johnny/Projects/yolo_tracking/tracking/generate_mot_results.py", line 51, in generate_mot_results
    dets_n_embs = np.concatenate(
                  ^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in concatenate
numpy.AxisError: axis 1 is out of bounds for array of dimension 1
```

**Comment by mikel-brostrom** [comment]
The error you are encountering, `numpy.AxisError: axis 1 is out of bounds for array of dimension 1`, suggests that one or both of the arrays you are trying to concatenate have fewer dimensions than expected. Specifically, this error occurs when axis=1 is specified for concatenation, but the arrays involved are not 2-dimensional. Given that you have already generated detections and embeddings, maybe it could be due to no detected objects in the frames. Are you running this on a custom dataset?

**Comment by johnnynunez** [comment]
> The error you are encountering, `numpy.AxisError: axis 1 is out of bounds for array of dimension 1`, suggests that one or both of the arrays have fewer dimensions than expected. Specifically, this error occurs when axis=1 is specified for concatenation, but the arrays involved are not 2-dimensional. Given that you have already generated detections and embeddings, maybe it could be due to no detected objects in the frames which would lead to empty arrays which would then lead to this script trying to concatenate 1D arrays, when expecting 2D. Are you running this on a custom dataset? I believe this is not failing for MOT17, but I haven't run this in a while.

It's working, it was just that I was getting DS_STORE, hence the other PR. Sorry!

**Comment by mikel-brostrom** [comment]
Alright. Nice 😄

**Pull request merged**
