### PR TITLE
Added formatting checks, reintroduced KF adapters, added more tests, pre-commit hooks

### PR DESCRIPTION
**Pull request by henriksod**
New changes:

- pre-commit hooks
- More **unit** tests
- Reintroduced KF adapters and tested them

Please check if there are any strange changes to the code since I had issues when pulling upstream master and reverting the adapter changes.

### CODE REVIEW

**Comment by mikel-brostrom** [comment]
Not sure I am a big fan of the makefile idea.  System python does not necessarily need to be the python which is used for the environment creation for example. It assumes a lot of things. It kinda bloats the root with files only used by make. Which I am not convinced of either.

I think contribution to the repo would be easier with a pre-commit which contains linting & unit-tests and not integration tests as that would take too long time. That can be configured in the pre-commit and wouldn't need individual black, flake8, etc configs at root level. 

The adapters could be merged as that is still part of the refactor. 

The pre-commit we can also try right away. 

But let's the makefile part sink in, let's put everything in separate MRs. I cannot see clearly how it is superior to a good pre-commit when it comes to contribution.

I try to follow the keep it simple, stupid principle as much as possible. Mostly for my own sake 😂.

**Comment by henriksod** [comment]
Feel free to add/modify to this PR, this is only a suggestion based on how I usually work. I like to not use GitHub limited features in case I want to migrate to and use other git platforms.

Let's go with pre-commit only if that is the preferred way.

**Comment by henriksod** [comment]
Remove makefile and updated PR description.

I also added test coverage check to CI, so any new code needs to be unit tested.

I believe why CI is so slow is because the track scripts are exeucted. I think creating unit tests would be much faster and coverwage would be traced.

**Comment by henriksod** [comment]
Managed to move black config to pre-commit. Flake8 config contains invalid according to YAML checker so I couldn't move those...

**Comment by mikel-brostrom** [comment]
Get all these errors on the adapters:

```
boxmot/motion/kalman_filter.py:638: [F821] undefined name 'kinematic_kf'
boxmot/motion/kalman_filter.py:640: [F721] syntax error in doctest
boxmot/motion/kalman_filter.py:641: [F721] syntax error in doctest
boxmot/motion/kalman_filter.py:642: [F721] syntax error in doctest
boxmot/motion/kalman_filter.py:646: [F821] undefined name 'kinematic_kf'
boxmot/motion/kalman_filter.py:647: [F821] undefined name 'saved_K'
boxmot/motion/kalman_filter.py:649: [F721] syntax error in doctest
boxmot/motion/kalman_filter.py:650: [F721] syntax error in doctest
boxmot/motion/kalman_filter.py:651: [F721] syntax error in doctest
boxmot/motion/kalman_filter.py:1413: [F821] undefined name 'x'
boxmot/motion/kalman_filter.py:1413: [F821] undefined name 'P'
boxmot/motion/kalman_filter.py:1413: [F821] undefined name 'z'
boxmot/motion/kalman_filter.py:1413: [F821] undefined name 'H'
```

**Comment by mikel-brostrom** [comment]
Everything else is amended but cannot push my changes due to these error on pre-commit

**Comment by henriksod** [comment]
This is the Kalman filter, not the adapters. I can have a look.
________________________________

**Comment by henriksod** [comment]
Looks like all these are from the doctests in the original implementation. I haven't touched these lines 😄 I guess we can remove all the doctests in the docstrings

**Comment by mikel-brostrom** [comment]
Last one... :sleepy: 

boxmot/motion/adapters/strongsort_kf_adapter.py:163: [F821] undefined name 'z'

**Comment by mikel-brostrom** [comment]
Should I just take back the old `gating_distance`?

https://github.com/mikel-brostrom/yolo_tracking/blob/e6c36f4464344e96ca28895412262598a3d1c20e/boxmot/motion/strongsort_kf.py#L176

**Comment by henriksod** [comment]
No it is just a change of variable from z to measurements. I can fix it. Don't know how to test this branch, I considered removing `only_position` since it is not used.

**Comment by mikel-brostrom** [comment]
Merged here: https://github.com/mikel-brostrom/yolo_tracking/pull/1001

**Pull request closed without merging**
