### PR TITLE
Feature/adaptive noise cov strong sort

### PR DESCRIPTION
**Pull request by henriksod**
**What is new?**
In a Kalman filter, you have additive noise in the covariance estimation step. This noise is typically tuned empirically to fit the model used for estimation. This adaptive approach, introduced by [this paper](https://arxiv.org/ftp/arxiv/papers/1702/1702.00884.pdf), adaptively calculates the Q and R noise matrices based on the residual error, left over from the innovation in the update step. The purpose is, that the model of the target in which you are trying to track is ambiguous since there is no restriction on what you can track. With that said, you cannot assume a noise model unless you specify what the tracker is supposed to track, and thus update the model accordingly.

**Reference Eval Results (yolov5m):**
```
HOTA: exp-pedestrian               HOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      RHOTA     HOTA(0)   LocA(0)   HOTALocA(0)
MOT17-04-FRCNN                     47.636    40.393    56.462    43.581    77.491    60.23     83.82     84.386    49.568    61.47     77.107    47.398
MOT17-05-FRCNN                     37.262    36.458    38.462    40.769    64.962    47.887    61.961    77.253    39.546    54.596    67.266    36.725
MOT17-09-FRCNN                     49.221    53.734    45.242    59.106    77.011    50.602    75.227    83.73     51.704    63.305    78.81     49.891
MOT17-10-FRCNN                     44.851    44.103    45.752    47.527    72.895    50.857    73.448    79.467    46.625    61.642    73.276    45.169
MOT17-11-FRCNN                     54.316    49.065    60.455    58.616    69.381    66.256    82.813    84.514    59.501    69.545    77.333    53.781
MOT17-13-FRCNN                     39.859    32.135    49.707    33.839    75.24     55.205    74.252    81.202    40.977    51.368    76.228    39.157
COMBINED                           46.681    41.243    53.269    45.1      74.473    58.266    79.964    82.831    48.944    60.906    75.859    46.203

CLEAR: exp-pedestrian              MOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
MOT17-04-FRCNN                     39.557    83.969    39.687    47.963    85.284    18.072    44.578    37.349    31.868    22810     24747     3936      62        15        37        31        639
MOT17-05-FRCNN                     31.907    75.11     32.89     47.824    76.204    8.2707    67.669    24.06     20.003    3308      3609      1033      68        11        90        32        294
MOT17-09-FRCNN                     61.014    82.103    61.803    69.277    90.262    42.308    53.846    3.8462    48.616    3689      1636      398       42        11        14        1         116
MOT17-10-FRCNN                     51.764    76.296    52.333    58.766    90.133    26.316    50.877    22.807    37.834    7545      5294      826       73        15        29        13        524
MOT17-11-FRCNN                     44.235    84.155    44.51     64.498    76.342    30.667    28        41.333    34.015    6086      3350      1886      26        23        21        31        145
MOT17-13-FRCNN                     38.37     78.133    38.842    41.909    93.182    19.091    38.182    42.727    29.206    4879      6763      357       55        21        42        47        283
COMBINED                           42.207    81.456    42.555    51.557    85.136    19.835    48.14     32.025    32.647    48317     45399     8436      326       96        233       155       2001

Identity: exp-pedestrian           IDF1      IDR       IDP       IDTP      IDFN      IDFP
MOT17-04-FRCNN                     56.173    43.882    78.027    20869     26688     5877
MOT17-05-FRCNN                     48.232    39.251    62.543    2715      4202      1626
MOT17-09-FRCNN                     60.348    53.333    69.489    2840      2485      1247
MOT17-10-FRCNN                     59.727    49.334    75.666    6334      6505      2037
MOT17-11-FRCNN                     61.707    56.92     67.373    5371      4065      2601
MOT17-13-FRCNN                     52.269    37.889    84.244    4411      7231      825
COMBINED                           56.543    45.392    74.956    42540     51176     14213

Count: exp-pedestrian              Dets      GT_Dets   IDs       GT_IDs
MOT17-04-FRCNN                     26746     47557     131       83
MOT17-05-FRCNN                     4341      6917      131       133
MOT17-09-FRCNN                     4087      5325      58        26
MOT17-10-FRCNN                     8371      12839     93        57
MOT17-11-FRCNN                     7972      9436      132       75
MOT17-13-FRCNN                     5236      11642     105       110
COMBINED                           56753     93716     650       484
```

**Eval Results (yolov5m):**
```
HOTA: exp-pedestrian               HOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      RHOTA     HOTA(0)   LocA(0)   HOTALocA(0)
MOT17-04-FRCNN                     45.377    40.419    51.27     43.58     77.704    54.08     85.946    84.495    47.213    58.124    77.332    44.949
MOT17-05-FRCNN                     38.906    36.753    41.712    41.01     65.39     48.041    68.065    77.368    41.273    56.014    67.604    37.867
MOT17-09-FRCNN                     52.267    55.011    49.785    60.046    78.197    53.365    80.66     84.088    54.672    66.594    79.737    53.1
MOT17-10-FRCNN                     41.825    44.031    39.867    47.416    72.995    44.266    73.818    79.473    43.47     57.76     73.223    42.294
MOT17-11-FRCNN                     51.303    49.031    53.922    58.519    69.527    57.53     84.634    84.61     56.156    65.677    77.477    50.884
MOT17-13-FRCNN                     39.062    32.049    47.889    33.747    75.121    52.148    76.845    81.107    40.16     50.425    76.013    38.329
COMBINED                           44.971    41.32     49.379    45.134    74.716    53.029    82.408    82.921    47.129    58.427    76.049    44.433

CLEAR: exp-pedestrian              MOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
MOT17-04-FRCNN                     39.424    84.112    39.603    47.844    85.307    16.867    45.783    37.349    31.823    22753     24804     3919      85        14        38        31        570
MOT17-05-FRCNN                     32.341    75.35     33.222    47.969    76.487    10.526    66.917    22.556    20.516    3318      3599      1020      61        14        89        30        269
MOT17-09-FRCNN                     62.535    82.235    62.967    69.878    91        42.308    53.846    3.8462    50.121    3721      1604      368       23        11        14        1         103
MOT17-10-FRCNN                     51.725    76.433    52.154    58.556    90.144    24.561    52.632    22.807    37.925    7518      5321      822       55        14        30        13        505
MOT17-11-FRCNN                     44.383    84.245    44.616    64.392    76.505    30.667    28        41.333    34.239    6076      3360      1866      22        23        21        31        129
MOT17-13-FRCNN                     38.095    77.879    38.533    41.728    92.887    20.909    34.545    44.545    28.864    4858      6784      372       51        23        38        49        257
COMBINED                           42.234    81.557    42.551    51.479    85.22     20.455    47.521    32.025    32.74     48244     45472     8367      297       99        230       155       1833

Identity: exp-pedestrian           IDF1      IDR       IDP       IDTP      IDFN      IDFP
MOT17-04-FRCNN                     51.918    40.518    72.244    19269     28288     7403
MOT17-05-FRCNN                     51.159    41.622    66.367    2879      4038      1459
MOT17-09-FRCNN                     65.307    57.728    75.177    3074      2251      1015
MOT17-10-FRCNN                     55.281    45.595    70.192    5854      6985      2486
MOT17-11-FRCNN                     57.498    52.946    62.906    4996      4440      2946
MOT17-13-FRCNN                     51.292    37.167    82.734    4327      7315      903
COMBINED                           53.748    43.108    71.362    40399     53317     16212

Count: exp-pedestrian              Dets      GT_Dets   IDs       GT_IDs
MOT17-04-FRCNN                     26672     47557     159       83
MOT17-05-FRCNN                     4338      6917      128       133
MOT17-09-FRCNN                     4089      5325      54        26
MOT17-10-FRCNN                     8340      12839     95        57
MOT17-11-FRCNN                     7942      9436      136       75
MOT17-13-FRCNN                     5230      11642     112       110
COMBINED                           56611     93716     684       484
```

**Additional Info**

Based on the results above, some more work will have to be done before merge, to ensure the eval results are at least better than the original implementation for all sequences. 

Currently, the adaptive solution performs better on some MOTA sequences, while worse on others.

This is a division from the following pull request: #596

### CODE REVIEW

**Comment by mikel-brostrom** [comment]
With crowdhuman_yolov5m

```
HOTA: exp77-pedestrian             HOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
MOT17-04-FRCNN                     45.377    40.419    51.27     43.58     77.704    54.08     85.946    84.495    47.213    58.124    77.332    44.949    
MOT17-05-FRCNN                     38.905    36.753    41.71     41.01     65.39     48.039    68.063    77.369    41.272    56.014    67.605    37.868    
MOT17-09-FRCNN                     52.267    55.011    49.785    60.046    78.197    53.365    80.66     84.088    54.672    66.594    79.737    53.1      
MOT17-10-FRCNN                     41.825    44.031    39.867    47.416    72.995    44.266    73.818    79.474    43.47     57.76     73.223    42.294    
MOT17-11-FRCNN                     51.303    49.03     53.923    58.518    69.526    57.53     84.633    84.61     56.156    65.677    77.476    50.884    
MOT17-13-FRCNN                     39.062    32.049    47.889    33.747    75.121    52.148    76.845    81.107    40.16     50.425    76.013    38.329    
COMBINED                           44.971    41.319    49.379    45.134    74.716    53.029    82.408    82.921    47.129    58.427    76.049    44.434    

CLEAR: exp77-pedestrian            MOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag      
MOT17-04-FRCNN                     39.424    84.112    39.603    47.844    85.307    16.867    45.783    37.349    31.823    22753     24804     3919      85        14        38        31        570       
MOT17-05-FRCNN                     32.341    75.351    33.222    47.969    76.487    10.526    66.917    22.556    20.517    3318      3599      1020      61        14        89        30        269       
MOT17-09-FRCNN                     62.535    82.235    62.967    69.878    91        42.308    53.846    3.8462    50.121    3721      1604      368       23        11        14        1         103       
MOT17-10-FRCNN                     51.725    76.433    52.154    58.556    90.144    24.561    52.632    22.807    37.925    7518      5321      822       55        14        30        13        505       
MOT17-11-FRCNN                     44.383    84.245    44.616    64.392    76.505    30.667    28        41.333    34.238    6076      3360      1866      22        23        21        31        129       
MOT17-13-FRCNN                     38.095    77.879    38.533    41.728    92.887    20.909    34.545    44.545    28.864    4858      6784      372       51        23        38        49        257       
COMBINED                           42.234    81.557    42.551    51.479    85.22     20.455    47.521    32.025    32.74     48244     45472     8367      297       99        230       155       1833      

Identity: exp77-pedestrian         IDF1      IDR       IDP       IDTP      IDFN      IDFP      
MOT17-04-FRCNN                     51.918    40.518    72.244    19269     28288     7403      
MOT17-05-FRCNN                     51.159    41.622    66.367    2879      4038      1459      
MOT17-09-FRCNN                     65.307    57.728    75.177    3074      2251      1015      
MOT17-10-FRCNN                     55.281    45.595    70.192    5854      6985      2486      
MOT17-11-FRCNN                     57.498    52.946    62.906    4996      4440      2946      
MOT17-13-FRCNN                     51.292    37.167    82.734    4327      7315      903       
COMBINED                           53.748    43.108    71.362    40399     53317     16212     

Count: exp77-pedestrian            Dets      GT_Dets   IDs       GT_IDs    
MOT17-04-FRCNN                     26672     47557     159       83        
MOT17-05-FRCNN                     4338      6917      128       133       
MOT17-09-FRCNN                     4089      5325      54        26        
MOT17-10-FRCNN                     8340      12839     95        57        
MOT17-11-FRCNN                     7942      9436      136       75        
MOT17-13-FRCNN                     5230      11642     112       110       
COMBINED                           56611     93716     684       484
```

**Comment by mikel-brostrom** [comment]
All the metrics go down a bit

**Comment by mikel-brostrom** [comment]
Have you run this again after the last pushes? @henriksod

**Comment by henriksod** [comment]
Yes, a bit better performance, but still not quite there yet. Looking into branching out some stuff that could potentially improve performance on the original KF for now

**Comment by henriksod** [comment]
Closing since this method did not provide better results in the end

**Comment by mikel-brostrom** [comment]
Do you have time to move the adaptive KF into a separate file? It would be much easier for me to get it merged :rocket:. Not sure if it is this one or the other which should be merged... :tired_face:

**Pull request closed without merging**
